module.exports = {
    folderApp: 'app',
    folderConfig: 'configs',
    folderPublic: 'public',
    folderUploads: 'uploads',
    folderRoutes: 'routes',
    folderViews: 'views',
    folderViewsAdmin: 'backend',
    folderViewsFrontend: 'frontend',
    folderHelpers: 'helpers',
    folderSchemas: 'schemas',
    folderModels: 'models',
    folderValidates: 'validates',
    folderMiddlewares: 'middlewares',
}