module.exports = {
    username: 'admin',
    password: 'admin',
    database: 'shopee',
    col_items: 'items',
    col_groups: 'groups',
    col_users: 'users',
    col_categories: 'categories',
    col_articles: 'articles',
    col_products: 'products',
    col_carts: 'carts',
    col_discounts: 'discounts',
    col_deliveries: 'deliveries',
    col_orders: 'orders',
    col_contacts: 'contacts',
    col_settings: 'settings',
    col_rss: 'rss',
    col_rss_articles: 'rssArticles',
}