
module.exports = {
    CHANGE_STATUS_SUCCESS: 'Cập nhật status thành công',
    CHANGE_STATUS_MULTI_SUCCESS: 'Có %d phần tử được cập nhật status thành công',
    CHANGE_ORDERING_SUCCESS: 'Cập nhật ordering thành công',
    CHANGE_SOLD_SUCCESS: 'Cập nhật Sold thành công',
    CHANGE_GROUP_ACP_SUCCESS: 'Cập nhật group ACP thành công',
    CHANGE_SPECIAL_SUCCESS: 'Cập nhật SPECIAL thành công',
    CHANGE_GROUP: 'Cập nhật group thành công',
    CHANGE_CATEGORY: 'Cập nhật CATEGORY thành công',
    DELETE_SUCCESS: 'Xóa phần tử thành công',
    DELETE_MULTI_SUCCESS: 'Có %d phần tử được xóa thành công',
    ADD_SUCCESS: 'Thêm mới phần tử thành công',
    EDIT_SUCCESS: 'Cập nhật thông tin phần tử thành công',
    ERROR_NAME: 'Chiều dài từ %d đến %d ký tự',
    ERROR_USERNAME_EXIST: 'Username đã tồn tại',
    ERROR_PASSWORD_CONFIRM: 'Password không khớp!',
    ERROR_LOGIN: 'Username hoặc Password không đúng!',
    ERROR_ORDERING: 'Phải là số nguyên lớn hơn %d và bé hơn %d',
    ERROR_STATUS: 'Vui lòng chọn Status!',
    ERROR_GROUP_ACP: 'Phải là một giá trị khác rỗng',
    ERROR_SPECIAL: 'Vui lòng chọn giá trị',
    ERROR_GROUP: 'Vui lòng chọn group!',
    ERROR_CATEGORY: 'Vui lòng chọn CATEGORY!',
    ERROR_FILE_REQUIRE: 'Vui lòng chọn file upload!',
    ERROR_FILE_LIMIT: 'Kích thước file không phù hợp!',
    ERROR_FILE_EXTENSION: 'Phần mở rộng file không hợp lệ!',

    LOAD_RSS_SUCCESS: 'Cập nhật RSS thành công',
};